apiVersion: apps/v1
kind: Deployment
metadata:
  name: devbox
  namespace: sf-gmail-com-levmckinney
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devbox
  template:
    metadata:
      labels:
        app: devbox
    spec:
      containers:
        - name: devbox
          image: levmck/malign-influence:main-devbox
          imagePullPolicy: Always
          command: ["/usr/sbin/sshd", "-D", "-e"]
          ports:
            - name: ssh
              containerPort: 22
          resources:
            requests:
              nvidia.com/gpu: 8
              nvidia.com/hostdev: 8
              memory: "512Gi"
              cpu: "32"
            limits:
              nvidia.com/gpu: 8
              nvidia.com/hostdev: 8
              memory: "512Gi"
              cpu: "32"
          volumeMounts:
            - name: workspace
              mountPath: /workspace
            - name: ssh-home
              mountPath: /home/dev/.ssh
            - name: ssh-keys
              mountPath: /tmp/ssh
              readOnly: true
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: false
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    set -eu
                    install -d -m 700 -o dev -g dev /home/dev/.ssh
                    install -m 600 -o dev -g dev /tmp/ssh/authorized_keys /home/dev/.ssh/authorized_keys
      volumes:
        - name: workspace
          emptyDir: {}
        - name: ssh-home
          emptyDir: {}
        - name: ssh-keys
          secret:
            secretName: ssh-authorized-keys
            items:
              - key: authorized_keys
                path: authorized_keys
---
apiVersion: v1
kind: Service
metadata:
  name: devbox-ssh
  namespace: sf-gmail-com-levmckinney
spec:
  type: ClusterIP
  selector:
    app: devbox
  ports:
    - name: ssh
      port: 2222
      targetPort: 22


