# .github/actions/setup/action.yml
name: Setup Repository
description: Sets up the repository and installs all dependencies using uv.
runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install UV
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
    - name: Install Python
      run: uv python install
    - name: Install Dependencies
      run: uv sync --all-extras --dev