name: setup

on: workflow_call

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
    # We install python with uv, so that we can
    - name: Install python
      run: |
        uv python install 

    - name: Install Dependencies
      run: uv sync --all-extras --dev