name: pyright 

on:
  pull_request:
    branches:
      - main

jobs:
  type-checking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install Python
        run: uv python install

      - name: Install Dependencies
        run: uv sync --all-extras --dev

      - name: Run Type Checking
        run: pyright
