name: ruff

on:
  pull_request:
    branches:
      - main

jobs:
  linting:
    name: Linting Workflow
    runs-on: ubuntu-latest
    steps:
      # Setup step
      - name: Setup Environment
        run: |
          echo "Setting up environment..."
          uv python install
          uv sync --all-extras --dev

      # Checkout step
      - name: Checkout Code
        uses: actions/checkout@v4

      # Linting step
      - name: Run Formatter and Linter
        run: |
          formatter_status=0
          linter_status=0
          
          # Run the formatter
          uv run ruff format --check || formatter_status=1
          
          # Run the linter
          uv run ruff check || linter_status=1
          
          # Fail at the end if either failed
          if [ $formatter_status -ne 0 ] || [ $linter_status -ne 0 ]; then
            echo "Linter or formatter failed"
            exit 1
          fi
