name: ruff
on:
  pull_request:
    branches: 
      - main

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: .github/workflows/base.yaml
    - name: Linter
      run: ruff check
    - name: Formatter
      run: ruff format --check