name: ruff

on:
  pull_request:
    branches: 
      - main

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install Python
        run: uv python install

      - name: Install Dependencies
        run: uv sync --all-extras --dev

      - name: Linter
        run: uv run ruff check
        continue-on-error: True
        id: linter

      - name: Formatter
        run: uv run ruff format --check
        if: success() || failure()
        id: formatter

      - name: Fail if Linter or Formatter Fails
        run: exit 1
        if: ${{ steps.linter.outcome == 'failure' || steps.formatter.outcome == 'failure' }}
