name: ruff
on:
  pull_request:
    branches: 
      - main

jobs:
  setup:
    uses: ./.github/workflows/base.yml
  linting:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Linter
      run: ruff check
    - name: Formatter
      run: ruff format --check